### PR TITLE
Update to M3 - Start

### PR DESCRIPTION
**Pull request by rodydavis**

### CODE REVIEW

**Review by guidezpl — APPROVED** [review]

**Review by guidezpl — CHANGES_REQUESTED** [review]
A few things

- I think the initial versions before the new theme code is defined should still use Material 3 
- Can you take a look at https://github.com/material-components/material-components-flutter-codelabs/issues/278 and https://github.com/material-components/material-components-flutter-codelabs/issues/285?

**Comment by rodydavis** [comment]
There is no theme defined yet on the material app. How do you set `useMaterial3` to true without a theme?

**Comment by guidezpl** [comment]
You would have to add a minimal light `theme: Theme.light(useMaterial3: true)` and dark `theme: Theme.dark(useMaterial3: true)` themes

**Comment by rodydavis** [comment]
Currently the app is only light theme, but i can add the place holder

**Comment by rodydavis** [comment]
Done!

**Review by guidezpl — APPROVED** [review]

**Pull request merged**
