### PR TITLE
Removing unnecessary use of cascade notation.

### PR DESCRIPTION
**Pull request by craftytrickster**

### CODE REVIEW

**Comment by craftytrickster** [comment]
@googlebot I signed it!

**Comment by craftytrickster** [comment]
I'm trying to learn dart/flutter, and this tutorial has been helpful so far. When following the samples, i noticed this double dot notation which seemed confusion and I had to look it up. It turns out, here it is completely unneeded.

**Comment by Renzo-Olivares** [comment]
LGTM

**Review by Renzo-Olivares — APPROVED** [review]
LGTM

**Pull request merged**
